### ISSUE TITLE
Can't see buy or sell info after the flip

### ISSUE THREAD

**Issue by leocavalcante** [playframework/play-websocket-scala#32]
Hi guys,
I was playing around with activator, then a ran Reactive Stocks sample, but when I click on a card to flip, it does not show any info.
![SS](http://image.prntscr.com/image/ae975881f4ea4d1fbb3a17e4c5e0cff9.jpg)

After a little hack into I found that this can be solved just adding a `z-index` property to `details-holder` CSS class. Too small change for a PR I guess.

**Comment by wsargent** [comment]
Thanks for the catch!
